### ISSUE TITLE
TODO: measuring the music strips for the 20 note music box set! (holes, notes and times)

### ISSUE THREAD

**Issue by JonesyLeo** [Wintergatan/Midi-to-laser-cutter#1]
Hi, Leo from Italy (Fablab Parma)!

I would like to collaborate to create the "converter" from MID to DXF (laser cuttable file)
Obviously, as shown in the attachment, the first things we need are **measures**:
- **A:** The height of the strip
- **B:** The diameter of a hole
- **C:** The distance from the lower C to the highest A.  (dividing this value per 19, we will obtain the height between two lines) 
- **D:** The distance between two consecutive notes (two vertical lines in the strip) in the time line. 

SO can publish this measures?
_I tried googling but, no matches,_

![music strips measures request](https://cloud.githubusercontent.com/assets/12800491/25525112/994e3980-2c0d-11e7-9f65-e62af7213ed1.jpg)

**Comment by Wintergatan2000** [comment]
Good thinking! I will try to add all this info in the WIKI file as soon as i have time to update it! 
I think for timing the cool thing with laser cutting is that we do not need to bother about measurement "D" we only need to put in a minmial space (music boxes can not play the same not too fast) I also think we should make the holes slightly longer than just a circle, will be better reading and look cool!

**Comment by Wintergatan2000** [comment]
For the 20 note music box:

Measurement A: 69,7 mm
Measurement B: 3 mm
Measurement C: 57 mm
Measurement D: 4 mm
Measurement "E" 8 mm
(Measurement "E" is the minimal required distance between two holes on the same line)

I think for timing the cool thing with laser cutting is that we do not need to bother too much about measurement "D" we only need to put in a minimal space "measurement E" (music boxes can not play the same not too fast) I also think we should make the holes slightly longer than just a circle, will be better reading and look cool!

**Comment by Yuleblinker** [comment]
Measurement B is quite flexible. It cannot exceed the distance between the mechanisms 'pluckers' (for want of a better word). I've used holes from 2mm up to 3mm. Also the only important bit of the hole is the trailing edge. This is what engages with the small wheels of the mechanism and rotates the 'plucker' to make play the note. This means the holes do not have to be circular - they could be square, hexagonal or some other shape. As long as the trailing edge is defined and engages correctly with the mechanism. It would be good to give the user some choice as to hole dimension and geometry

![mechanism](https://cloud.githubusercontent.com/assets/26853115/25529357/9b50cbb0-2c19-11e7-9cb2-8b96efae3f9f.png)

**Comment by JonesyLeo** [comment]
I forgot a fundamental data: **the thickness of the paper**!

Looking at the videos, it seems like a cardboard, with the thickness of a businesscard (300 grams/m3)...

[I use a 160 x 130 cm Lasercutter, [my baby!](http://fablabparma.org/portfolio/laser-cutter/) and the idea is to buy large panels of paper (the largest the machine can eat!) to build music strips of 160 cm each!]

**NOTE**
One of the customizable parameter would certainly be the maximum length of every strip.

**Comment by DrSkunk** [comment]
Doesn't the thickness of the paper depend on the laser cutter settings and not the supplied file?
And indeed, the length should be a parameter.

**Comment by JonesyLeo** [comment]
With my english, probably I messed up what I would to say! 🤣 

The thickness is a fundamental parameter in order to have the MusicBox operating good.
So, my question it's only here to let me buy a panel of cardboard with the right thickness!

(Sure I will find the right parametrization of the speed and power of the lasercutter, based on the thickness itself)

**Comment by Yuleblinker** [comment]
I don't know the GSM of the 20 note strips you can buy but I've just measured the thickness of one and its 0.4mm.

**Comment by DrSkunk** [comment]
I'll probably pick up a music box to try it out on, are there any recommendations?

**Comment by Yuleblinker** [comment]
I have this one and I think it might be the same type as Martin uses. It has 20 notes:
http://www.grand-illusions.com/acatalog/Large_Music_Box_Set.html

**Comment by rzinurov** [comment]
![scan-170328-0003](https://cloud.githubusercontent.com/assets/8040747/25548057/e3d89272-2c6a-11e7-89d6-ac0181cc7eb0.jpg)

**Comment by DrSkunk** [comment]
Info is added to the wiki https://github.com/Wintergatan/Midi-to-laser-cutter/wiki/Music-box-and-strip-measurements
