### ISSUE TITLE
Please solve before wednesday morning: Credits, names and social links for Potential Wintergatan Youtube video

### ISSUE THREAD

**Issue by Wintergatan2000** [Wintergatan/Midi-to-laser-cutter#12]
Hey all! I MIGHT make a video this wednesday about your progress, its not entirely decided what video i will make, if i dont make it this week i will make it another week. 

SO:

Can You please answer this todo with the following:

IF i make a video covering this project and process, how do you want to be credited:

(only fill in the info you want me to share, or none if you do not want to be mentioned)

-Name/alias
-Picture 
-Country 
-Role in the project
-Social media links (youtube channels are great here)
-Other info you think i should share with the viewers about the project

Can i share the current version somehow?

If you have video, pictures, or media that i can use in the video that covers your process, can you please also post a link where i can download them.

Im gone tomorrow tuesday so i have only wednesday morning to make the video so i will use the information i find in this post by then.

OK, talk soon! Best/ Martin

**Comment by DrSkunk** [comment]
- Sebastiaan Jansen
- ![14657459_10210802576768883_89478851675679595_n](https://cloud.githubusercontent.com/assets/1058174/25590843/5528fe6e-2eb2-11e7-8f12-a4580f92dc12.jpg)
- Belgium
- Project manager, user interface
- twitter: https://twitter.com/Wh1tebird , instagram: https://www.instagram.com/sebastiaan__jansen/ , website: http://sebastiaanjansen.be/


You can use the layout mockup picture: https://github.com/Wintergatan/Midi-to-laser-cutter/issues/9

**Comment by ChemiCalChems** [comment]
Txema Ynzenga [Pronunciation](https://www.youtube.com/watch?v=aPzmgJTHG1I) . ChemiCalChems

![whatsapp image 2017-05-01 at 21 50 52](https://cloud.githubusercontent.com/assets/9658223/25594475/057cafb4-2ec1-11e7-8630-6d17970c17d7.jpeg)

Madrid, Spain

General programmer, mainly focused on background logic such as file processing.

https://twitter.com/ChemiCalChems 
https://github.com/ChemiCalChems

Martin, when you start editing the video, tell me so I can send you the latest version of a graph looking like this https://www.youtube.com/watch?v=1gWsPJ6Hk80&feature=youtu.be I'll keep it updated in this comment anyway, every time a major update comes along.

- Newest version as of time of edit: https://www.youtube.com/watch?v=V0XsEpeSArk&feature=youtu.be

Planning to start a youtube channel with projects and stuff https://www.youtube.com/channel/UChUyfLljEvcNbripydMQivA

**Comment by ChemiCalChems** [comment]
Also if you want to use the newest version of the program at any point, you can just go [here](https://wintergatan.github.io/Midi-to-laser-cutter/). That'll always be the last version of the software that's pushed onto the repository, guaranteed.

**Comment by Yuleblinker** [comment]
**Andrew Craigie**
Yuleblinker

**Cheesy Picture**
![andrew_craigie](https://cloud.githubusercontent.com/assets/26853115/25620446/4eb139c2-2f46-11e7-9780-46a435e85109.png)

**Location**
Glasgow, Scotland

**Role**
Contributer

**Links:**
Website:     http://yuleblinker.com/
YouTube:   https://www.youtube.com/channel/UC7MHShKZtUMKj_U-2UQb0vA
Twitter:      @Yuleblinker

**Project Info**
I think this could be a fantastic tool to use in schools with children. Not only for studying, appreciating and play music but for triggering creative ideas. Punched paper strips could be used by makers for all sorts of things. I mention a few here:  [Can you hear the drums Fernado?](https://github.com/Wintergatan/Midi-to-laser-cutter/issues/11)

**Media**
First cut of strips output from a prototype of the application:
![canon in c](https://cloud.githubusercontent.com/assets/26853115/25620852/9bf32df2-2f47-11e7-950c-46fcde909e97.png)

**Comment by ianespana** [comment]
**Ian Ramirez-España C.**
Heracles421/ianespana

**Picture**
![profile_picture](https://q6jvxq-ch3301.files.1drv.com/y4mXWV3-D_7w_YPdFt1PUZbrQt1xT02m6xIYEQjyHlhEoC_E21p2k-EuBRAFIUMVtXbe4hM8Lk1eQw0CHhHZCHyYvXj5J5TAf2ce0PYFDEqE9nHxemra3fA-EBzBk59LgjFyM6TsgJuwUPgWAYRKSHhMZg1_ockSXePIq_WIcfitZ46i5o9mDV_sLQME3mNPWux_RKTOtjB3eNaH2NCEXuGSw)

**Location**
Mexico City, Mexico

**Role**
General programmer, focus on logic to translate MIDI to other formats (DXF, SVG, etc)

**Links:**
GitHub: https://github.com/ianespana
Twitter: @ianespana97
YouTube: https://www.youtube.com/channel/UC8dxAqI3pmIGmoDmUSdPD8A

**Comment by emosenkis** [comment]
**Eitan Mosenkis**
emosenkis

**Picture**
![Photo](https://emosenkis.github.io/profile.jpg)

**Location**
Israel

**Role**
General programmer

**Links**
https://github.com/emosenkis

**Comment by Wintergatan2000** [comment]
Super, thanks everyone for sending in this info, im makin a video today about this, under severe time pressure now as i want to try to get this in a nice story format, and my internet always takes like 3 hours to upload haha so... anyway, talk more soon and hope you will like the video!

**Comment by Lars-Kristian** [comment]
**Lars-Kristian Johansen**
Lars-Kristian

**Location**
Tromsø, Norway

**Role**
Made the Music Box Editor Prototype.

**Comment by ChemiCalChems** [comment]
Video was awesome! Closing.
