### ISSUE TITLE
Add instructions for building the app

### ISSUE THREAD

**Issue by emosenkis** [Wintergatan/Midi-to-laser-cutter#14]
I'm not sure how to rebuild the app.[hash].js

**Comment by Lars-Kristian** [comment]
I have not commited the source code for the MusicBox Editor. Only the working application.
I will add the source code later on. When most of my ideas are working.

**Comment by emosenkis** [comment]
Could you please commit the source code even before it's all working so the rest of us can also contribute to making it work?

**Comment by inconsistent-brick** [comment]
The source was the fist thing I looked for as well. Might want to add an explanation to the readme.md for those who come looking. You should also probably also clarify how (and if) others can get involved.

**Comment by Lars-Kristian** [comment]
I am not comfortable with it, but sure lets see what happens. 
I will do it when I come home.

**Comment by Lars-Kristian** [comment]
Done.
