### ISSUE TITLE
TODO: Extracting notes and timing of notes from the .MID file, to use later

### ISSUE THREAD

**Issue by ChemiCalChems** [Wintergatan/Midi-to-laser-cutter#2]
Somewhere down the line, we will need to get into the .MID file, and when and which notes are played, by looking at the [MIDI file format](http://www.personal.kent.edu/~sbirch/Music_Production/MP-II/MIDI/midi_file_format.htm). 

We should be most interested in [channel voice messages](http://www.personal.kent.edu/~sbirch/Music_Production/MP-II/MIDI/midi_channel_voice_messages.htm), especially in note on and off events. These include
- MIDI channel: we shouldn't really need to pay attention to this, because we should only be working with one channel:
- Key: the key that was pressed. If the key is out of range of our paper, we may need to transpose it to another key, as shown in the [music box programming tutorial](https://youtu.be/HjBhO9iqEc0?t=6m33s). 
- Velocity: this roughly maps to note volume, which we don't care about either.

**Comment by DrSkunk** [comment]
The decision we need to make is that we either only accept completely valid midi-files, or that we 'fix' it by transposing it. We can also offer a different program to automatically transpose the notes.

**Comment by ChemiCalChems** [comment]
I would say we could fix them.

**Comment by DrSkunk** [comment]
If we fix them, it's maybe a good idea to also supply the fixed midi file so the creator can play it back with his software to check it.

**Comment by ChemiCalChems** [comment]
Granted.

**Comment by Wintergatan2000** [comment]
Maybe we can implement my sampled music box sound in the software so you can play back the song directly in the software before punching. Maybe thats overcomplicating and hard on the servers but would be really useful.

**Comment by DrSkunk** [comment]
@Wintergatan2000 It's possible to do, we'll just put it on a lower priority than the rest of the functionality.

**Comment by ianespana** [comment]
https://github.com/ianespana/Wintergatan-Laser-MIDI
