### ISSUE TITLE
#21 Correct and add scales in scaleandmusicbox.js

### ISSUE THREAD

**Issue by weirdsound** [Wintergatan/Midi-to-laser-cutter#21]
The naming scheme used for the scales in *[scaleandmusicbox.js](https://github.com/Wintergatan/Midi-to-laser-cutter/blob/master/inc/scaleandmusicbox.js)* is incorrect. The list of scales needs to be extended.

**Comment by djflorio** [comment]
@weirdsound which scales are named incorrectly? All I see is that Phrygian is spelled incorrectly (unless that's an alternate spelling?)

Are you saying that some of those modes don't match up with the intervals presented? I haven't personally checked all of them, so I'm not sure, but the few that I've checked seem correct.

**Comment by weirdsound** [comment]
@djflorio Not the scales themselves. The categories. E.g. "aeolian" is certainly not a major scale. I'm preparing a more comprehensive list containing about 90 scales (including chromatic, various pentatonic, etc.). Feel free to join the discussion over at [http://gitter.im/Wintergatan/Midi-to-laser-cutter]
