### ISSUE TITLE
TODO: Choose language to code in

### ISSUE THREAD

**Issue by ChemiCalChems** [Wintergatan/Midi-to-laser-cutter#7]
More and more people are talking about making a web app, so it seems we will choose JS at the end, but this has to be discussed.

**Comment by emosenkis** [comment]
+1 for something that can run in a browser, ideally without even needing a server. This could also include Rust or any other language that supports emscripten (which compiles other languages into asm.js or WebAssembly)

**Comment by ChemiCalChems** [comment]
We are finally going for a web app, using JS as our frontend for all the processing,
