### ISSUE TITLE
Layout preview

### ISSUE THREAD

**Issue by DrSkunk** [Wintergatan/Midi-to-laser-cutter#9]
Currently I mocked up this layout. It's using a three column layout so the missing settings can be added. 
![afbeelding](https://cloud.githubusercontent.com/assets/1058174/25558193/c4db85ac-2d21-11e7-803c-2ba2c167b8ab.png)

Thoughts on the general style?

**Comment by Pierstoval** [comment]
Maybe have a little SVG schema describing the workspace. It doesn't need to be updated with input values, but at least having a picture with all measurements values visible might help people understand how these values are used on a _real_ laser cutting machine

**Comment by DrSkunk** [comment]
The only variables on a laser cutter are usually the line color, workspace size and file format. What other input values are you thinking of?

**Comment by Pierstoval** [comment]
If you're saying that only line color, workspace size and file format are related to laser cutter, then maybe add a specific fieldset "Laser cutter settings" to know there's a difference between midi-to-laser output & machine config.

**Comment by DrSkunk** [comment]
Good idea, I then propose to move all settings to below the preview together with a heading so it's clear that it's for the laser cutter.

**Comment by DrSkunk** [comment]
Has been migrated to https://github.com/Wintergatan/MIDIPunch/issues/1
